### ISSUE TITLE
Documentation request - using templates

### ISSUE THREAD

**Issue by danjac** [python-babel/flask-babel#1]
There should be a short introduction in how to use gettext, trans etc in Jinja the jkji2 templates - it's not obvious from the docs that the jinja2 i18n ext is used and that the user does not need to configure this separately.

**Comment by txdywy** [comment]
5

**Comment by mchobby** [comment]
You can also have a look to the Miguel's Flask Mega Tutorial.

http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xiv-i18n-and-l10n

Very nice

**Comment by erayerdin** [comment]
![image](https://user-images.githubusercontent.com/2399084/39019769-18574292-4433-11e8-9882-d95ba08a621d.png)

Just keeping the custom...

**Comment by tvb** [comment]
Even during Covid we celebrate!
![twenty_candles_by_danthienne_d4b3jmm-fullview](https://user-images.githubusercontent.com/1263414/95497571-d18d9180-09a2-11eb-82e9-b99d88e4b6e4.jpg)

**Comment by mcejp** [comment]
This was fixed in 2016, but in the meantime, the note in the docs seems to have disappeared again.
