### ISSUE TITLE
Test with Babel

### ISSUE THREAD

**Issue by pythonstory** [python-babel/flask-babel#102]
Hello,

Flask-Babel extension works fine when it is run as an application, but I have a problem when running tests.

```
(venv) C:\projects\rabiang\repo>python -m flask test
ERROR

======================================================================
ERROR: setUpClass (test_basics.BasicsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\rabiang\repo\tests\test_basics.py", line 17, in setUpClass
    app = create_app(config='../test.cfg', blueprints=blueprints)
  File "C:\projects\rabiang\repo\app\app.py", line 23, in create_app
    configure_extensions(app)
  File "C:\projects\rabiang\repo\app\app.py", line 73, in configure_extensions
    @babel.localeselector
  File "C:\projects\rabiang\venv\lib\site-packages\flask_babel\__init__.py", line 127, in localeselector
    'a localeselector function is already registered'
AssertionError: a localeselector function is already registered

----------------------------------------------------------------------
Ran 0 tests in 0.004s

FAILED (errors=1)
```

You can check the files related to Babel as follows:

[app/app.py](https://github.com/pythonstory/rabiang/blob/master/app/app.py) 
[tests/test.py](https://github.com/pythonstory/rabiang/blob/master/tests/test_basics.py)
[run.py](https://github.com/pythonstory/rabiang/blob/master/run.py)
[babel.cfg](https://github.com/pythonstory/rabiang/blob/master/babel.cfg)
[test.cfg](https://github.com/pythonstory/rabiang/blob/master/test.cfg)

I use Blueprints and ```create_app()``` factory.

I tried to use ```@classmethod``` ```setUpClass``` instead of ```setUp``` to make sure that call ```app.py``` only once, but it doesn't work.

I  actually asked this issue  at stackoverflow.com, but I didn't get answer at all.

Please, help me. What's wrong with me?

**Comment by pythonstory** [comment]
I moved ```@babel.localeselector``` and ```@babel.timezoneselector``` decorated function declaration into ```app/extensions.py``` from ```app/app.py``` so that they are not loaded.

It seems to be good, but I want to know a better way if you have. Thank you.

**Comment by zgoda** [comment]
I know this is old and closed with some workaround but I found another. If you follow application structure with app factory then in your `configure_extensions()` you can just check if `babel.locale_selector_func` is not `None` and set up `.localeselector` only if it not set already.
