### ISSUE TITLE
Incompatible with multiple apps with different translations

### ISSUE THREAD

**Issue by asteinlein** [python-babel/flask-babel#107]
Flask-Babel stores an app instance in `self.app`, which will be set in `init_app()` regardless. This means that using the same Babel instance with multiple apps (each app running `babel_instance.init_app(app)` doesn't work as expected: Only the translations from the last app configured will be used.

**Comment by davidism** [comment]
For reference, Flask-SQLAlchemy implements a [`get_app`](https://github.com/mitsuhiko/flask-sqlalchemy/blob/fa78d3909ead6d17c1d673e059195a35b98a865b/flask_sqlalchemy/__init__.py#L927-L941) method and uses that anywhere an app is required.

**Comment by timothyqiu** [comment]
The same goes for `localeselector` and `timezoneselector`. They are bound to the Babel instance, so can't be configured separately for different apps 😢 

FYI, Flask-SQLAlchemy and Flask-Mail store app specific states in `app.extensions['NAME']`.

**Comment by guydavis** [comment]
Hi, I am trying out version 3.0 that was just released and am hitting the deprecation in `__init__.py` of a Flask app of:
```
@babel.localeselector
def get_locale():
    ....
```
What is the recomended approach to use instead of above, to be compatible with Flask-Babel v3.0?   Thanks!
