### ISSUE TITLE
Incompatible with blueprints having different locale settings.

### ISSUE THREAD

**Issue by rohitkrai03** [python-babel/flask-babel#112]
I have two blueprints with different translations but since Babel instance is initialised on the main app only once it makes it impossible to have multiple babel instances with different locale settings.

**Comment by rohitkrai03** [comment]
A similar issue created 6 months back but not solved till now.

https://github.com/python-babel/flask-babel/issues/107

**Comment by b0g3r** [comment]
Hi! I decided to use this template: https://github.com/b0g3r/flask_i18n_tg_bot/blob/master/tg_bot/main.py
