### ISSUE TITLE
RecursionError Flask-Babel

### ISSUE THREAD

**Issue by oomnis** [python-babel/flask-babel#141]
I'm facing an issue (?) with Flask-Babel when used with other modules (e.g., Flask-Admin(

Error is happening when I reach other blueprint.

builtins.RecursionError
RecursionError: maximum recursion depth exceeded while calling a Python object

here's how I call Flask-Babel in my app __init__.py:

`babel.init_app(app)`
[...]

	@babel.localeselector
	def get_locale(): 
		  return request.accept_languages.best_match(current_app.config['LANGUAGES'])

I solved the problem by editing flask_babelex\__init__.py:

	def get_locale():
		ctx = _request_ctx_stack.top
		if ctx is None:
			return None

		locale = getattr(ctx, 'babel_locale', None)

		if locale is None:
			babel = ctx.app.extensions.get('babel')

			if babel is None:
				locale = _DEFAULT_LOCALE
			else:
				if babel.locale_selector_func is not None:
					rv = babel.locale_selector_func()
					if rv is None:
						locale = babel.default_locale
					else:
						locale = rv #Replace the below original line by this one
						#locale = babel.load_locale(rv)
				else:
					locale = babel.default_locale

			ctx.babel_locale = locale
		return locale

Any idea why the  `locale = babel.load_locale(rv)` line is causing this RecursionError ?

Thanks

**Comment by TkTech** [comment]
This repository is for flask-babel, not the fork [flask-babelex](https://github.com/mrjoes/flask-babelex), which you seem to be using.
