### ISSUE TITLE
Pass extra args to babel functions (decimal_quantization)

### ISSUE THREAD

**Issue by wjdp** [python-babel/flask-babel#142]
Babel have added `decimal_quantization` to `format_decimal`, `format_currency`, `format_percent`, and `format_scientific`. Flask-Babel cannot pass this arg through when using the equivalent proxy functions so users cannot use these new features.

For reference here is Flask-Babel's `format_percent`

```python
def format_percent(number, format=None):
    """Return formatted percent value for the locale in request

    :param number: the number to format
    :param format: the format to use
    :return: the formatted percent number
    :rtype: unicode
    """
    locale = get_locale()
    return numbers.format_percent(number, format=format, locale=locale)
```

And the signature of the underlying Babel function:

```python
def format_percent(number, format=None, locale=LC_NUMERIC, decimal_quantization=True):
```

Should Flask-Babel hard code args in like this, or should it use the `*args, **kwargs` pattern to pass through extra args to the underlying Babel functions?

**Comment by TkTech** [comment]
Removing this method in favor of direct imports from babel in v2. See #164.
