### ISSUE TITLE
How to Change Languages with URL PREFIX ? 

### ISSUE THREAD

**Issue by bekab95** [python-babel/flask-babel#143]
With Flask Can I change translations with url prefix ? for example mysite.com/en and mysite.com/ka

**Comment by tvuotila** [comment]
You can always write:
```python
@babel.localeselector
def get_locale():
    return request.url.split('/', 2)[1]
```

**Comment by ufo911** [comment]
I want to make url_prefix logic correctly 
https://stackoverflow.com/questions/49496761/two-language-flask-site-with-or-without-blueprints
this is my example works but I think there is cleaner solution for multiple lang prefixes with cookie

**Comment by tvuotila** [comment]
Use `{% trans %}` tags in templates http://jinja.pocoo.org/docs/2.10/templates/#i18n

Do the setup https://pythonhosted.org/Flask-Babel/#flask.ext.babel.Babel
Remember to do the "Translating Applications" part also.

You probably want a locale selector like:
```python
@babel.localeselector
def get_locale():
    return getattr(g, 'lang_code', None)
```

**Comment by ufo911** [comment]
I will try but if you have a working example please refer

**Comment by tvuotila** [comment]
> I will try but if you have a working example please refer

I cannot share any of the ones I have worked on, but at the end of [this blog](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xiv-i18n-and-l10n), there is a working example of application with i18n.

**Comment by ufo911** [comment]
I have seen many examples but it was tricky for me to get fully clean solution for translating..
