### ISSUE TITLE
Split LazyString in another package?

### ISSUE THREAD

**Issue by sblondon** [python-babel/flask-babel#150]
LazyString has been merged in https://github.com/python-babel/flask-babel/commit/c8344d02331f2988cb0b2e9f56366015bc3b317c from https://github.com/mitsuhiko/speaklater

I use Babel and LazyString but not Flask.
What do you think about maintaining LazyString as an external library? flask-babel would then depend on Babel and Babel-LazyString (the new package).

**Comment by TkTech** [comment]
It's too trivial to justify making a dependency, and changes exceptionally rarely. If you want to pull it out into a separate package and make improvements to it, that's fine with me.

**Comment by sblondon** [comment]
Ok, thanks for your reply.
