### ISSUE TITLE
Import fails flask.ext.babel

### ISSUE THREAD

**Issue by Dreamsorcerer** [python-babel/flask-babel#155]
The home page of this project gives the import as: `from flask.ext.babel import Babel`

This fails as this functionality appears to have been removed from Flask. Update the documentation to: `from flask_babel ..`

See for example: https://stackoverflow.com/questions/50589906/why-am-i-getting-no-module-named-flask-ext-with-flask-autodoc

**Comment by Monduiz** [comment]
flask.ext is a deprecated style of importing. This should be updated in the documentation to reflect current version of Flask.

**Comment by hharutyunyan** [comment]
Seams this is already resolved a long while ago. https://github.com/python-babel/flask-babel/pull/118
@TkTech @Dreamsorcerer

**Comment by Dreamsorcerer** [comment]
Then someone needs to deploy the latest docs to the website, which still clearly states flask.ext.babel in the very first example on the home page.
https://pythonhosted.org/Flask-Babel/

**Comment by zormit** [comment]
I just came across this, as I wondered about the `flask.ext.babel` import. How is the documentation on pythonhosted.org generated, what is there to do to update it?

**Comment by TkTech** [comment]
All occurrences of this should be resolved. Note, the pythonhosted documentation seems to be out of my control. Please use the updated https://flask-babel.tkte.ch.
