### ISSUE TITLE
Deprecation warning with Werkzeug==0.16.0

### ISSUE THREAD

**Issue by paxet** [python-babel/flask-babel#159]
I've updated werkzeug to its last release in a project and now I can see:

> DeprecationWarning: The import 'werkzeug.ImmutableDict' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.datastructures import ImmutableDict' instead.
>     from werkzeug import ImmutableDict

There is no hurry for the update, but must be considered.

**Comment by davidism** [comment]
Duplicate of #157

**Comment by paxet** [comment]
Good job, I didn't notice as it's a closed issue and the fix not merged to master yet :(

**Comment by davidism** [comment]
It is merged into dev. They will make a release when they can. This can be closed.

**Comment by TkTech** [comment]
There will be a non-breaking release this weekend with a number of bugfixes.
