### ISSUE TITLE
Getting import Error

### ISSUE THREAD

**Issue by naveen-varshney** [python-babel/flask-babel#162]
`from flask_babel import Babel, gettext
/usr/local/lib/python3.6/dist-packages/flask_babel/__init__.py:19: in <module>
    from werkzeug import ImmutableDict
E   ImportError: cannot import name 'ImmutableDict'`

Flask-1.1.1 
Flask-Babel-0.12.2
Werkzeug-1.0.0

I think there is some new version is released of Werkzeug.
Kindly help me out.

**Comment by TkTech** [comment]
Update flask-babel.

**Comment by Obed101** [comment]
Update Babel from [here](https://pypi.org/project/Flask-Babel/)  
I believe it will solve your problem
