### ISSUE TITLE
Remove all format_* wrappers

### ISSUE THREAD

**Issue by TkTech** [python-babel/flask-babel#164]
Our API is never up to date with babel (ex: #142), and we do not cover the entire babel API. Our wrappers add no real value, and add a lot of surface area for test coverage. Just like flask-wtforms did way back in version 0.9, we should focus on just being the glue between flask and babel.

- [x] format_datetime
- [x] format_date
- [x] format_time
- [x] format_timedelta
- [x] format_number
- [x] format_decimal
- [x] format_currency
- [x] format_percent
- [x] format_scientific

As part of this, we need to improve the documentation to show better examples of using `get_locale` and `get_timezone`.

**Comment by homeworkprod** [comment]
Hi @TkTech,

while I do agree with this move, I'd like to point out that while Flask-Babel's `format_date` rebases according to the time zone, Babel's `format_date` *does not*. This might be a bad surprise for users after upgrading to v3.0.

I have [raised an issue against Babel](https://github.com/python-babel/babel/issues/805), hoping that Babel will gain this ability. But I guess it could use some more backing.
