### ISSUE TITLE
how to get specific string translation (which is not currently the locale)?

### ISSUE THREAD

**Issue by alnikolaj** [python-babel/flask-babel#172]
Let's say I have a string in English, locale="en", e.g. "computer" and its Spanish translation, locale="es" translation, would be "computadora".

If the website is currently set to English, how could still access that specific string but translated to Spanish without changing the global locale for the whole website?

Something like = gettext('computer', language='es') ?

Thanks

**Comment by zgoda** [comment]
Use [Python stdlib](https://docs.python.org/3/library/gettext.html) `gettext.bindtextdomain()` and then `gettext.gettext()` to retrieve translation for particular message. Note `bindtextdomain()` will load the whole message catalog.

**Comment by TkTech** [comment]
You just use `with force_locale('es'):` and everything in the block will be changed.
