### ISSUE TITLE
destroy docs on pythonhosted.org

### ISSUE THREAD

**Issue by zormit** [python-babel/flask-babel#176]
Thanks for the updated documentation (this is a new issue in reply to #155 )!

[Here](https://github.com/pypa/pypi-legacy/issues/700#issuecomment-378470711) is a description on how to "destroy" the legacy pythonhosted docs. It was in the past maintained via PyPI. I dont have a PyPI account, but I'd be curious if that works.

Also I'd like to mention that there's some kind of operational risk involved in the decision that you're hosting the documentation on your private server: What happens when you decide to not maintain it anymore? I can see how it's nice for a maintainer to have it under their control, also you probably get some visibility for your own page which is nice since you're taking the time to maintain this package.

Maybe you could host a mirror on readthedocs.org, just to be on the safe side?
https://docs.readthedocs.io/en/stable/intro/import-guide.html

Not sure if it's worth the trouble though and maybe it's confusing to have two places (as we have right now, with pythonhosted.org).

**Comment by davidism** [comment]
I don't remember exactly how, but you can message the PyPI team to get a redirect added to the old docs URL.

**Comment by TkTech** [comment]
I will add a redirect. It's easy to do, you just upload an index.html with an old fashion redirect tag to pypi.

It is not my private server - it's hosted on GitHub pages. It is updated automatically from the gh-pages branch.

**Comment by TkTech** [comment]
Aside from that, if I decide to no longer maintain the package, I won't just abandon it. A new maintainer will be found and the keys passed. However, I don't see that happening. With the changes coming in #174 maintaining this package will be very little effort.

**Comment by davidism** [comment]
As far as I know you can't upload to pythonhosted anymore. The PyPI admins can add a redirect in the server config manually though.

**Comment by TkTech** [comment]
You're 100% right, only button under documentation now is Destroy. Will throw them an email.

**Comment by TkTech** [comment]
Done
