### ISSUE TITLE
Include rest of speaklater module

### ISSUE THREAD

**Issue by jwag956** [python-babel/flask-babel#177]
Flask-Babel already includes the LazyString class. 
The speaklater module (which hasn't changed since 2012!) has 3 methods:

is_lazy_string
make_lazy_string
make_lazy_gettext

adding those would reduce a package dependency and not have multiple implementations of LazyString (interestingly enough - Flask-Babel exports LazyString as a public class while speaklater doesn't (_LazyString)).

**Comment by TkTech** [comment]
None of those three methods seem worth including. They add no functionality.
`is_lazy_string is just `isinstance(x, LazyString)`. `make_lazy_string` is just `LazyString()`.

Additionally, I want to remove the included speaklater and use the lazy proxy in upstream babel's support module, which is a requirement anyways.

**Comment by jwag956** [comment]
Sounds good - yes - those are easily added to my library. My thought was around making Flask-Babel a drop in replacement for Flask-BabelEx...
