### ISSUE TITLE
Extracting translator comments

### ISSUE THREAD

**Issue by Porrumentzio** [python-babel/flask-babel#186]
I want to add translator comments on *.py files, using flask-babel module, and seems that the traditional Gettext _extracted comment_ method\* does **not** work, as there are no such comments on .pot.

\* This structure:
``` python
# A comment
_("String to translate")
```

The documentation on [Babel](http://babel.pocoo.org/en/latest/messages.html#translator-comments) says:
> **Note:**  
> Whether translator comments can be extracted depends on the extraction method in use. The Python extractor provided by Babel does implement this feature, but others may not.

So is this the case for Flask-Babel? Is there any workaround or method to extract these comments? Am I doing something wrong?

**Comment by Porrumentzio** [comment]
This seems to be solved with the `--add-comment='tag'` option appended to the pybabel extract command. Anyway, comments starting with that tag are displayed to translators with the tag:
![irudia](https://user-images.githubusercontent.com/61913683/120826479-c8b58580-c55a-11eb-937b-77a7d59af347.png)

And letting the tag empty adds programmer's comments that must not be shown to translators. Is this right? Wouldn't the tag be used for identify which comments to extract, but hidden on POT files?

**Comment by TkTech** [comment]
Extraction is the domain of Babel, not flask-babel, which is just the glue.
