### ISSUE TITLE
Modifying translation files' structure

### ISSUE THREAD

**Issue by Porrumentzio** [python-babel/flask-babel#187]
Seems that the unique way to structure translations with (flask-)babel is this:
```
/translations
|___messages.pot
|
|___/es
|...|___/LC_MESSAGES
|.......|____messages.po
|___/eu
|...|___/LC_MESSAGES
|.......|____messages.po
```
I want to use this kind of structure instead:
```
/translations
|___messages.pot
|___es.po
|___eu.po

```

Is this possible?

**Comment by TkTech** [comment]
No. `LC_MESSAGES` is actually the name of the translation category. It can be LC_MESSAGES, LC_NUMERIC, LC_CURRENCY, yada yada. The directory structure has meaning to tools that work with gettext catalogs.
