### ISSUE TITLE
Flash messages not localised when a variable is in string

### ISSUE THREAD

**Issue by Porrumentzio** [python-babel/flask-babel#198]
Hi, I'm Porru, the person in charge of [LiberaForms](https://liberaforms.org).
I have noticed that when a flash message has some variable in it, the string will not be localised. As a result, any flash message containing variables, marked with `%` or with `.format()`, is showed in the source language.

This happens using `Flask v. 2.0.2`, `Flask-Babel v. 2.0.0` and `Babel v. 2.9.1`

Maybe we are doing something wrong or maybe this is a bug, so any help is appreciated to figure out what is this about

**Comment by Porrumentzio** [comment]
Yes of course. You can see some of them here:
https://gitlab.com/liberaforms/liberaforms/-/blob/main/liberaforms/views/form.py#L446
https://gitlab.com/liberaforms/liberaforms/-/blob/main/liberaforms/views/form.py#L398
https://gitlab.com/liberaforms/liberaforms/-/blob/main/liberaforms/views/form.py#L205

**Comment by TkTech** [comment]
Yes, you aren't using it correctly. What you're doing won't work in any translation tool.

```py
    flash(_("This form is already shared with %s" % new_editor.email), 'warning')
```

This is telling it that the string you want translated is literally `This form is already shared with editor@editor.com`, rather than `This form is already shared with %s`. You pass the variables as arguments, and I also recommend you use named variables.

```py
    flash(_("This form is already shared with %(email)s", email=new_editor.email), 'warning')
```

**Comment by TkTech** [comment]
There is no difference. Pass your arguments as always.

```py
ngettext("Deleted one answer", "Deleted %(num)s answers", total_answers, num=total_answers)
 ```
