### ISSUE TITLE
Support temporary language switch inside a request

### ISSUE THREAD

**Issue by rslinckx** [python-babel/flask-babel#2]
It would be nice to be able to stash the current language somewhere and use another one for a while during a request execution.

The main use-case I see is sending out emails with Flask-Email. The email should be translated according to the recipient's language and not the current user's language.

Something like:

    from flaskext.babel import stash, unstash

    # do stuff with current user's language
    print _('foo')
    # Now switch to th recipient language
    stash(new_lang=recipient.language)
    send email with i18n tags
    unstash()
    # Now the language is back to the current user's lang

Well the API is terrible, but you get the idea..

**Comment by jmagnusson** [comment]
A nice API for this would be awesome.

Btw last commit to this project was almost three years ago. What happened?...

**Comment by kvesteri** [comment]
Our company took over this project couple of months ago. We promise there will be a commitfest to this project soon. This is probably the first issue we are going to address.

**Comment by ThiefMaster** [comment]
@kvesteri: Nice to hear this! Are you also going to include everything from Flask-BabelEx (which is a fork of this project anyway)?

**Comment by kvesteri** [comment]
I have to see the differences between this and Flask-BabelEx and go through those case by case. So yes, at least many things will be included.

**Comment by jmagnusson** [comment]
@kvesteri That's great news! 😀Sign me up for incorporation of Flask-BabelEx's features as well. I think the only reason I started using it was for its py3 compatibility though.
