### ISSUE TITLE
Documentation site is a 404

### ISSUE THREAD

**Issue by solsticedhiver** [python-babel/flask-babel#202]
The documentation is supposed to be at https://flask-babel.tkte.ch/

But this returns a 404

**Comment by TkTech** [comment]
I enabled Github's domain verification for the tkte.ch domain, and this seems to have (sensibly) removed the flask-babel.tkte.ch CNAME from this repo. Since I don't control this org, and can't verify it, the link has been changed back to the long, default github pages url.
