### ISSUE TITLE
Babel cannot find words in flask_caching blocks

### ISSUE THREAD

**Issue by serkin** [python-babel/flask-babel#208]
If I have html file content like

```
<html>
{% cache 3600, request.url %}
<tag>{{ _('h1') }}</tag>
{% endcache %}
</html>
```

And run 
`pybabel extract -F babel.cfg -k _l -o translations/messages.pot .`

Flask Babel cannot find new words in {% cache %} block

**Comment by TkTech** [comment]
Extraction is not handled by flask-babel, we're just the glue. Jinja2 registers a babel extractor plugin here, https://github.com/pallets/jinja/blob/main/setup.cfg#L44, which ultimately calls https://github.com/pallets/jinja/blob/main/src/jinja2/ext.py#L644.

Either Jinja2 or flask_caching need to add support for the {% cache %} tag.
