### ISSUE TITLE
ngettext implementation is incompatible with standard ngettext

### ISSUE THREAD

**Issue by redspider** [python-babel/flask-babel#27]
The classic ngettext interface is:

```
def ngettext(self, singular, plural, n):
```

Flaskext-babel extends this to be:

```
def ngettext(self, singular, plural, n, **variables):
```

in order to assist with doing the translation and interpolation steps in one go. Unfortunately applications relying on the standard interface can break, if they do the following:

```
str = ngettext('I like a car','I like %(cars)s cars',cars)
return str % dict(cars=cars)
```

In this case, if cars = 2, ngettext should return:

```
I like %(cars)s
```

Instead however the application crashes on https://github.com/mitsuhiko/flask-babel/blob/master/flaskext/babel.py#L479

```
    return t.ungettext(singular, plural, num) % variables
```

because flaskext is forcing an interpolation against variables, which is empty.

It is explicitly not the fault of callers expecting the normal behaviour, the standard behaviour of ngettext is well defined. Flaskext is breaking a number of dependent applications and libraries silently, including wtforms which makes use of this functionality in the Length validator.

**Comment by TkTech** [comment]
Fixed in #88, thank you!
