### ISSUE TITLE
Mention Flask-Assets Jinja2 extension in docs/examples

### ISSUE THREAD

**Issue by joostdevries** [python-babel/flask-babel#47]
Considering the assumption that a lot of people use Flask-Assets in their projects, it might be nice to mention the necessity of including their Jinja2 filter (`webassets.ext.jinja2.AssetsExtension`) in babel.cfg when using Flask-Babel. (They've done the same thing vice-versa).

See https://github.com/miracle2k/flask-assets/pull/27

**Comment by TkTech** [comment]
Documentation is going to be re-written, but I think for now the preference is for things that integrate with *us* to document (as flask-assets has done perfectly). If *we* integrate with something, we'll document it on our side.
