### ISSUE TITLE
Not extracting strings from some files

### ISSUE THREAD

**Issue by osleg** [python-babel/flask-babel#52]
I have a base.html file and navbar.html file.
The navbar.html is included in base.html and base extended in other templates.
The problem is that babel does not extract strings from navbar.html even though i can see it read it.

extraction log
```extracting messages from app/templates/navbar.html (extensions="jinja2.ext.autoescape,jinja2.ext.with_", encoding="utf-8")
```

babel.cfg
```[python: **.py]
[jinja2: **.htm*]
encoding = utf-8
extensions=jinja2.ext.autoescape,jinja2.ext.with_
```

What could be the problem?

**Comment by digitalformula** [comment]
> If you set `slient=false` under the `[jinja2]` section, you may get more information on why it's failing. I had the same problem and it turned out that I didn't have all the necessary jinja2 extensions registered (I was using webassets, which creates an `{% assets %}` tag.
> 
> Hope this helps!

Wow, almost 5 years later and this reply just solved the exact issue I was having.  Freakin' brilliant - thanks!
