### ISSUE TITLE
Slow importing of 'flask.ext.babel'

### ISSUE THREAD

**Issue by agordon** [python-babel/flask-babel#54]
Hello,

In my tiny new Flask application, importing 'flask.ext.babel' takes relatively long time (~8 seconds). Is there a way to improve it?

Trying to pin-point the problem, I did this:
```
$ python
Python 2.7 (r27:82500, Apr  6 2013, 21:24:05) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask
>>> import babel
>>> import pytz
>>> import flask.ext.babel
```

All except the last "import" completes instantaneously. But the last import of 'flask.ext.babel' takes about 8 seconds (this is before any of my Flask code actually runs).

I'm using this version:
```
$ pip show flask-babel
---
Name: Flask-Babel
Version: 0.9
Location: /usr/local/lib/python2.7/site-packages
Requires: Flask, Babel, speaklater, Jinja2
``` 

Any suggestions ?

Thanks,
 -gordon

**Comment by TkTech** [comment]
I've been unable to reproduce this with master. Very little import-time work is done by flask-babel, the majority of it being simple compatibility checks (can I import X, else import Y).
