### ISSUE TITLE
Norwegian Language "no" not used

### ISSUE THREAD

**Issue by viksok** [python-babel/flask-babel#61]
Babel 1.3, Flask-Babel 0.9.6
Babel fails to resolve "no" locale. The catalog is initiated, no fuzzys appear but it doesn't use the translations.
No such problem with "nb" locale.

BTW. Pyramid Babel works well with "no" locale

**Comment by kumy** [comment]
I also have problem with `no` locale not visually translated. I'm using

```
$ pip list|grep -i babel 
Babel (2.5.1)
Flask-Babel (0.11.2)
```
