### ISSUE TITLE
lazy_ngettext not working

### ISSUE THREAD

**Issue by davelandry** [python-babel/flask-babel#69]
When running `pybabel extract -k lazy_pgettext` on my project, the context of each `lazy_pgettext` is being parsed as the translation string.

**Comment by erickwilder** [comment]
Same error here. I'll take a look on what can be done to fix this. 
@davelandry have you found anything useful on this topic?

**Comment by davelandry** [comment]
I honestly even forgot I made this issue. I ended up just not using lazy mode on the project I was working on at the time.

**Comment by andreymal** [comment]
@TkTech same problem for me. Should I open a new issue?

**Comment by homeworkprod** [comment]
I have the same issue. `pybabel extract -F babel.cfg -k lazy_gettext -k lazy_pgettext -o messages.pot .` picks up what's passed to `lazy_gettext` but not `lazy_pgettext`.

On my first localization run I used just `pgettext` in the code and added the `lazy_` prefix later, but now that these are in place, this is no longer an option, as the diff created by `pybabel extract` became quite big and the lines removed again conflict with the new ones in the translated messages file.

**Comment by homeworkprod** [comment]
Then again, this is probably an issue with Babel itself, not Flask-Babel.

**Comment by born2discover** [comment]
Having stumbled upon this issue myself, I managed to find a solution.

To make `lazy_pgettext` work as expected, one needs to specify the way its occurrences should be parsed (as per the [docs](https://babel.pocoo.org/en/latest/cmdline.html#extract)).

The command should be instead `pybabel extract -k lazy_pgettext:1c,2` (notice the `:1c,2` part, which indicates that the first argument is a context string and the second one is a string to be translated).

**Comment by homeworkprod** [comment]
Ha, good call! I figured this out a few months ago as well after digging in the code.

My current extraction invocation looks like this:
```sh
$ pybabel extract -F babel.cfg --keywords 'lazy_gettext lazy_ngettext:1,2 lazy_pgettext:1c,2 lazy_npgettext:1c,2,3' -o messages.pot .
```
