### ISSUE TITLE
Empty string should be translated to whatever translated and not the PO nonsense  info

### ISSUE THREAD

**Issue by AlmogCohen** [python-babel/flask-babel#74]
I know that the GNU gettext is overriding whatever we think and just replace empty string with nonsense information. Its time to stop the crime! Its time that we can control the empty string!

Most likely, it will be just super convenient to translate empty strings to empty strings!

I just make gzilion of problems that empty string is translated to this wierd PO information. Is anybody see any reason to keep working that way?

Reference:
http://www.gnu.org/software/gettext/manual/gettext.html#MO-Files

**Comment by TkTech** [comment]
This isn't just a preference, but in the "specification" of gettext. We're not going to change 30 years of expected behavior, as odd as it might seem
