### ISSUE TITLE
list_translations should always return the default locale

### ISSUE THREAD

**Issue by ghost** [python-babel/flask-babel#75]
list_translations() currently only returns the default locale if no translation files exist. I believe it should always return the default locale.

For example, if my keys are in English, I will not have a .mo for English, but it is still a valid locale and would be returned as such if I hadn't yet translated into German.

Furthermore, I think that the default locale should be returned even if the translations folder does not exist (currently an empty list is returned in this case) - why is that any different to an empty translations folder?

**Comment by rlam3** [comment]
+1

**Comment by lafrech** [comment]
I also think that the default locale should always be included.

Should we send a PR?
