### ISSUE TITLE
[support] how to translate this?

### ISSUE THREAD

**Issue by somenxavier** [python-babel/flask-babel#80]
Hi,

I want to translate this:
```
 Powered by {{meta['title']}} version {{meta['version']}}
```
How to do it?

Thanks,

**Comment by mchobby** [comment]
Hi, just use parametrized translation:

{{ _('Powered by %(title)s version %(version)s', title = meta['title'], version=meta['version']) }}

**Comment by somenxavier** [comment]
Thanks
