### ISSUE TITLE
Accent ruined in Babel Flask.. please help

### ISSUE THREAD

**Issue by mchobby** [python-babel/flask-babel#85]
Hi, I have some problem with babel translation into a flask application. The translated accent é is rendered as Ã© whereas the untranslated é still appears properly as é. At this stage, (and after lot os search and check) I do need some help to fix this.

* Using Python 3 under Win 7.
* html (Jinja templates) are UTF-8 encoded on the disk (checked)
* the message po file is UTF-8 encoded on the disk (checked)

It sounds that babel is reading/rendering the translation resource like ansi file? 
I did noticed exactly the same rendering behaviour when I do display the po file content into a file viewer not supporting utf-8 (this can easily been simulated in PSPAD editor by switching format from UTF-8 to textonly ).

Any idea (additional information) to troubleshoot this issue?

**Comment by mchobby** [comment]
Additionnal note: I notice that I could have accent by introducing html entity within the translation (eg: &eacute; ).
Strange, BabelFlask isn't not supposed to make auto-escaping?

**Comment by TkTech** [comment]
@mchobby Would you be able to provide a minimal reproducible example?

**Comment by mchobby** [comment]
Sorry, I have been very busy... and solved the problem in a very simple way.
I did migrate my development environment to Linux Mint.
As the Operating System, Python3, file storage are all unicode based... all problems has disappeared when I did fixed the accents in the translation files. As the hosting at pythonanywhere is also unicode compliant I'm now quite comfortable with the translation process.
