### ISSUE TITLE
Elect a new maintainer?

### ISSUE THREAD

**Issue by dahlia** [python-babel/flask-babel#87]
Flask-Babel project hasn’t seemed updated about 2+ years.  There are 20+ pull requests waiting review as well.

If the current maintainer has no enough time to maintain the project, how about electing a new maintainer?

**Comment by kvesteri** [comment]
Hi, our company took over this project at the end of last year. We promise there will be a commit fest soon that address the most significant issues.

**Comment by rlam3** [comment]
New Release pelase!

**Comment by TkTech** [comment]
Done, and done.
