### ISSUE TITLE
Flask-Babel=0.10.0 breaks cyrillic translations for ngettext

### ISSUE THREAD

**Issue by georgthegreat** [python-babel/flask-babel#92]
Even if the formula for nplurals returns 2, ngettext uses 1st template for substitution.

Everything returns to normal upon reverting back to 0.9.

Here is the MWE: https://github.com/georgthegreat/mwe

Run it using `make debug` (you have to setup virtualenv using provided `requirements.txt`).
Open you browser using http://localhost:5000
The result with Flask-Babel==0.9.0 is:
```
Format according to rule #0 using locale=ru: 1
Format according to rule #1 using locale=ru: 3
Format according to rule #2 using locale=ru: 8
```

The result with Flask-Babel==0.10.0 is:
```
Format according to rule #0 using locale=ru: 1
Format according to rule #1 using locale=ru: 3
Format according to rule #1 using locale=ru: 8
```

Third line differs and this is the bug introduced.

**Comment by TkTech** [comment]
Thank you for the ticket, I'm taking a look at this.

**Comment by TkTech** [comment]
So that required diving into the cpython and babel gettext implementations. Fun times.

@georgthegreat give the master branch a try.

**Comment by georgthegreat** [comment]
Thanks!
I've checked version 0.11.1 - works fine for me.
