### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by dahlia** [python-babel/flask-babel#98]
Flask-Babel currently does not provide any changelog.  The lack of it make consumers hard to trace when features were introduced.

Also, it would be better if docs utilize Sphinx’s [`.. versionadded::`](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded) and [`.. versionchanged::`](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionchanged) directives as well.

**Comment by alexkiro** [comment]
+1 for a changelog.
