### ISSUE TITLE
Translator comments

### ISSUE THREAD

**Issue by pors** [python-babel/flask-babel#99]
.po files support translator comments, see https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

Is there a way to add translator comments in or near the gettext() call? I have seen mentions of adding a comment before the gettext() call, but that doesn't seem to work (at least not in jinja2).

**Comment by nberrios** [comment]
This thread might be of help to you:
https://github.com/pallets/jinja/issues/591#issuecomment-224974742

**Comment by TkTech** [comment]
Closing as this is not a flask-babel issue. Thank you for that link @nberrios.
